main = ".open-next/worker.js"
name = "pushfwd"

compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

[build.upload]
format = "service-worker"

[assets]
directory = ".open-next/assets"
binding   = "ASSETS"

[vars]
PROTECT = "rnQWfo8pI0WP+2nCNyC5LRRWZPg7Msg+wcL+4JMxwc="
SID = '2835537AVC'
OPENNEXT_DISABLE_INCREMENTAL_CACHE = "true"

# [[services]]
#  binding = "WORKER_SELF_REFERENCE"
#  service = "redrectorxcz"

# R2 buckets (uncomment and configure if you're using R2)
#[r2_buckets]
#  binding = "NEXT_INC_CACHE_R2_BUCKET"
#  bucket_name = "<BUCKET_NAME>"

